// 12 Slide definitions: title, description, layout type, and questions
const SLIDES = [
  {
    index: 0,
    title: 'Cover / Title Slide',
    description: 'Make a bold first impression. This is what investors see first.',
    layout: 'cover',
    icon: '🚀',
    questions: [
      { id: 'q0_1', text: 'What is the name of your startup / project?', type: 'text', placeholder: 'e.g. EduReach AI' },
      { id: 'q0_2', text: 'Write a tagline — one powerful sentence that describes what you do.', type: 'text', placeholder: 'e.g. Connecting rural students to world-class tutors using AI.' },
      { id: 'q0_3', text: 'What is your team name and who are the members? (Name – Role)', type: 'textarea', placeholder: 'e.g. Team Ignite: Arjun – CEO, Priya – CTO, Rahul – Design Lead' },
    ],
  },
  {
    index: 1,
    title: 'The Problem',
    description: 'Define the pain. Show investors why this problem urgently needs solving.',
    layout: 'two-col',
    icon: '⚡',
    questions: [
      { id: 'q1_1', text: 'What is the core problem you are solving? (2–3 sentences)', type: 'textarea', placeholder: 'e.g. 60% of rural students lack access to quality coaching for competitive exams...' },
      { id: 'q1_2', text: 'Who suffers from this problem? (Target audience)', type: 'text', placeholder: 'e.g. Students in Tier-2/3 cities aged 14–22' },
      { id: 'q1_3', text: 'How big is this problem? (Any numbers, statistics, or personal story)', type: 'textarea', placeholder: 'e.g. 300 million students in India lack quality educational resources...' },
      { id: 'q1_4', text: 'Why does this problem exist today / why hasn\'t it been solved?', type: 'textarea', placeholder: 'e.g. Existing solutions are expensive and require high-speed internet...' },
    ],
  },
  {
    index: 2,
    title: 'The Solution',
    description: 'Introduce your product clearly. Make it simple and compelling.',
    layout: 'two-col',
    icon: '💡',
    questions: [
      { id: 'q2_1', text: 'What does your product/service do? (Explain like you\'re telling a friend)', type: 'textarea', placeholder: 'e.g. Our app connects students to AI tutors that adapt to their learning pace...' },
      { id: 'q2_2', text: 'What makes your solution unique compared to alternatives?', type: 'textarea', placeholder: 'e.g. We work offline, support 6 regional languages, and cost only ₹99/month...' },
      { id: 'q2_3', text: 'What is the core technology or method behind your solution?', type: 'text', placeholder: 'e.g. Adaptive AI + Regional NLP + Offline-first PWA' },
      { id: 'q2_4', text: 'Describe your product in one sentence. (Elevator pitch)', type: 'text', placeholder: 'e.g. Netflix for education, built for Bharat.' },
    ],
  },
  {
    index: 3,
    title: 'Product Demo / How It Works',
    description: 'Show the product in action. Walk investors through the experience.',
    layout: 'steps',
    icon: '🖥️',
    questions: [
      { id: 'q3_1', text: 'Walk us through how a user uses your product step by step. (3–5 steps)', type: 'textarea', placeholder: 'Step 1: Student downloads app\nStep 2: Takes a 5-min diagnostic test\nStep 3: Gets a personalized study plan...' },
      { id: 'q3_2', text: 'What are the top 3 key features of your product?', type: 'textarea', placeholder: '1. AI-powered adaptive tests\n2. Offline mode for low-connectivity areas\n3. Live doubt-solving in regional languages' },
      { id: 'q3_3', text: 'Do you have a prototype, MVP, or working demo? (Yes/No + describe)', type: 'textarea', placeholder: 'e.g. Yes — we have a working Android app with 200 beta users in Vizag.' },
    ],
  },
  {
    index: 4,
    title: 'Market Opportunity',
    description: 'Show the size of the prize. Investors need to know this is worth pursuing.',
    layout: 'market',
    icon: '📊',
    questions: [
      { id: 'q4_1', text: 'Who is your target customer? (Describe your ideal user)', type: 'textarea', placeholder: 'e.g. Class 10–12 students in semi-urban India preparing for NEET/JEE...' },
      { id: 'q4_2', text: 'How large is your target market? (TAM, SAM, SOM — estimate if unsure)', type: 'textarea', placeholder: 'e.g. TAM: ₹2.5 lakh crore EdTech market | SAM: ₹30,000 crore K-12 segment | SOM: ₹500 crore in 3 years' },
      { id: 'q4_3', text: 'What industry/sector does your startup belong to?', type: 'text', placeholder: 'e.g. EdTech / Rural Education / AI' },
      { id: 'q4_4', text: 'What trends are driving demand for your solution?', type: 'textarea', placeholder: 'e.g. Post-COVID digital adoption, India\'s 600M smartphone users, NEP 2020...' },
    ],
  },
  {
    index: 5,
    title: 'Business Model',
    description: 'Show how you make money. Keep it simple and believable.',
    layout: 'canvas',
    icon: '💰',
    questions: [
      { id: 'q5_1', text: 'How does your startup make money? (Revenue streams)', type: 'textarea', placeholder: 'e.g. Monthly subscription + School licensing + Premium content packs' },
      { id: 'q5_2', text: 'What is your pricing model?', type: 'text', placeholder: 'e.g. Freemium — ₹0 basic, ₹99/month premium' },
      { id: 'q5_3', text: 'Who pays you — the end user, businesses, or someone else?', type: 'text', placeholder: 'e.g. Students pay directly; schools pay for institutional plans' },
      { id: 'q5_4', text: 'What is your estimated revenue per customer per month?', type: 'text', placeholder: 'e.g. ₹99/month per student; ₹5,000/month per school' },
    ],
  },
  {
    index: 6,
    title: 'Traction & Validation',
    description: 'Show you\'re not just an idea — show proof this works.',
    layout: 'traction',
    icon: '📈',
    questions: [
      { id: 'q6_1', text: 'Have you tested your product with real users? (Yes/No — describe)', type: 'textarea', placeholder: 'e.g. Yes — 200 students used the beta for 3 months in Vizag & Rajahmundry...' },
      { id: 'q6_2', text: 'Any early users, pilot customers, signups, or letters of intent?', type: 'textarea', placeholder: 'e.g. 500 signups, 2 schools signed MoUs, 1 NGO partnership...' },
      { id: 'q6_3', text: 'What feedback have you received from potential customers?', type: 'textarea', placeholder: 'e.g. "This saved my son 2 hours of commute daily!" — parent from Vijayawada' },
      { id: 'q6_4', text: 'Any awards, recognitions, hackathon wins, or press mentions?', type: 'textarea', placeholder: 'e.g. Winner — SRKR Techfest 2024; Featured in The Hindu EdTech roundup' },
    ],
  },
  {
    index: 7,
    title: 'Competitive Landscape',
    description: 'Acknowledge the competition and show why you win.',
    layout: 'competitive',
    icon: '🏆',
    questions: [
      { id: 'q7_1', text: 'Who are your top 3 competitors? (Name them)', type: 'text', placeholder: 'e.g. BYJU\'s, Unacademy, Vedantu' },
      { id: 'q7_2', text: 'How is your solution better than each competitor?', type: 'textarea', placeholder: 'e.g. BYJU\'s: Too expensive for rural students. We cost 10x less.\nUnacademy: No offline mode. We work without internet.' },
      { id: 'q7_3', text: 'What is your unfair advantage — something they cannot easily copy?', type: 'textarea', placeholder: 'e.g. Hyperlocal content in Telugu + relationship with 50 rural schools' },
      { id: 'q7_4', text: 'What two axes best distinguish you? (e.g. Cost vs. Quality)', type: 'text', placeholder: 'e.g. Affordability (X-axis) vs. Accessibility / Offline-readiness (Y-axis)' },
    ],
  },
  {
    index: 8,
    title: 'Go-To-Market Strategy',
    description: 'Explain how you\'ll reach your first customers and grow.',
    layout: 'gtm',
    icon: '🎯',
    questions: [
      { id: 'q8_1', text: 'How will you acquire your first 100 customers?', type: 'textarea', placeholder: 'e.g. Direct outreach to 10 schools + WhatsApp groups + college campus drives...' },
      { id: 'q8_2', text: 'What are your top 3 marketing/distribution channels?', type: 'textarea', placeholder: 'e.g. 1. School partnerships\n2. YouTube study content\n3. Referral program' },
      { id: 'q8_3', text: 'What is your launch plan? (Timeline, phases)', type: 'textarea', placeholder: 'e.g. Month 1–2: Beta with 5 schools\nMonth 3–4: Public launch in Andhra Pradesh\nMonth 6: Expand to Telangana' },
      { id: 'q8_4', text: 'Do you have any partnerships or collaborations planned?', type: 'textarea', placeholder: 'e.g. SRKR Engineering College, District Education Office, local coaching centers' },
    ],
  },
  {
    index: 9,
    title: 'Team',
    description: 'Investors bet on people. Show why your team is built to win.',
    layout: 'team',
    icon: '👥',
    questions: [
      { id: 'q9_1', text: 'Introduce each team member: Name, Role, and one key skill or background.', type: 'textarea', placeholder: 'Arjun Kumar – CEO – 3 years in EdTech product management\nPriya Sharma – CTO – Full-stack developer, built 2 apps\nRahul Nair – Design – UX designer, 50+ mobile app designs' },
      { id: 'q9_2', text: 'Why is YOUR team the right team to solve this problem?', type: 'textarea', placeholder: 'e.g. We all grew up in Tier-3 towns and faced this problem firsthand. We\'ve lived the pain...' },
      { id: 'q9_3', text: 'Do you have any mentors, advisors, or faculty support?', type: 'textarea', placeholder: 'e.g. Dr. Ramesh Babu (HOD, SRKR) – technical advisor; IIC Cell – institutional support' },
    ],
  },
  {
    index: 10,
    title: 'Financials & Roadmap',
    description: 'Show financial potential and a clear path forward.',
    layout: 'financials',
    icon: '📉',
    questions: [
      { id: 'q10_1', text: 'What are your financial projections for Year 1, 2, and 3? (Revenue estimate)', type: 'textarea', placeholder: 'e.g. Year 1: ₹5L | Year 2: ₹25L | Year 3: ₹1.2Cr' },
      { id: 'q10_2', text: 'How much funding/investment are you seeking? (If any)', type: 'text', placeholder: 'e.g. ₹25 lakhs seed funding' },
      { id: 'q10_3', text: 'What will you use the funds for? (Break down into categories)', type: 'textarea', placeholder: 'e.g. 40% Product Dev, 30% Marketing, 20% Operations, 10% Legal/Compliance' },
      { id: 'q10_4', text: 'What are your top 3 milestones for the next 12 months?', type: 'textarea', placeholder: '1. Launch in 20 schools\n2. Reach 5,000 active students\n3. Achieve ₹5L monthly recurring revenue' },
    ],
  },
  {
    index: 11,
    title: 'The Ask / Closing',
    description: 'End with a bang. State your ask clearly and leave them inspired.',
    layout: 'closing',
    icon: '🎤',
    questions: [
      { id: 'q11_1', text: 'What exactly are you asking for today?', type: 'textarea', placeholder: 'e.g. We are seeking ₹25L in seed funding + mentorship from industry leaders + pilot partnerships with 5 schools.' },
      { id: 'q11_2', text: 'What is your vision — where will your startup be in 5 years?', type: 'textarea', placeholder: 'e.g. The go-to education platform for 10 million rural students across South Asia.' },
      { id: 'q11_3', text: 'Write a powerful closing statement or call to action.', type: 'textarea', placeholder: 'e.g. Every child deserves a world-class education. Help us make that a reality.' },
      { id: 'q11_4', text: 'Provide your contact details (Email, Phone, LinkedIn, Instagram)', type: 'textarea', placeholder: 'e.g. hello@edureach.ai | +91 98765 43210 | linkedin.com/in/arjunkumar' },
    ],
  },
];

export default SLIDES;
